# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptb', '0002_auto_20170723_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pet_friendly',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
